apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.iac.backendjava.name }}
  labels:
    app: {{ .Values.iac.name }}
spec:
  replicas: {{ .Values.iac.backendjava.replicas }}
  strategy:
    type: {{ .Values.iac.backendjava.strategy }}
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Values.iac.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.iac.name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.iac.backendjava.name }}
          image: {{- if .Values.iac.google.project }} gcr.io/{{ .Values.iac.google.project }}/{{- end }}{{ .Values.iac.backendjava.image.repository }}:{{ .Values.iac.backendjava.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: {{ .Values.iac.backendjava.name }}
              containerPort: {{ .Values.iac.backendjava.port }}
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.iac.backendjava.resources.limits.cpu }}
              memory: {{ .Values.iac.backendjava.resources.limits.memory }}
            requests:
              cpu: {{ .Values.iac.backendjava.resources.requests.cpu }}
              memory: {{ .Values.iac.backendjava.resources.requests.memory }}
              
