apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.iac.backendjava.name }}
  labels:
    app: {{ .Values.iac.backendjava.name }}
spec:
  selector:
    app: {{ .Values.iac.backendjava.name }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
