apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.iac.frontendpython.name }}
  labels:
    app: {{ .Values.iac.frontendpython.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.iac.frontendpython.name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
